Crown-Commercial-Service/digitalmarketplace-visual-regression

- Dockerfile
- README.md
- scripts/build-and-push-docker-image.sh
We do this to set up a docker group and jenkins user inside the
container that map to those on the host. This means files created by the
container (e.g. backstop_data/bitmaps_test) will be editable by the
Jenkins job we are running, allowing us to delete them as appropriate to
keep disk usage low.
> Adds a Dockerfile that we can use to build our own image of BackstopJS.

- backstop_data/engine_scripts/casper/user.js
- config.js
The user list page is now restricted to the new "framework manager" role
which we don't have a user account set up for yet.  And the page will be
going away altogether in the next week or so, so not worth patching up
that test right now.
Category and Sourcing accounts added, with one page tested for each new
type of user.
It's not clear to me from the README what I'll need to do if/when this is approved and merged... what is the Docker stuff for? Do I need to build and push a new Docker image before the changes will be picked up? Or will I be able to just run the job in Jenkins and it will pull the new version in?
> Add Category and Sourcing admin pages and remove user list page test

- config.js
Following route change for this page in supplier-frontend:
https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/799
> Update url for 'What buyers will see' page

- config.js
Some URLs have changed in the supplier sign-up flow.
> Update for new supplier sign-up flow

- CHANGELOG.md
- Dockerfile
- scripts/build-and-push-docker-image.sh
The visual regression tests Dockerfile creates a user called 'jenkins' and specifies it's UID. This UID has to match with the owner of the directory that gets mounted as a volume into the container. Currently the UID in the Dockerfile is hardcoded to match the UID of the jenkins user on the Jenkins box. This is bad. If the jenkins user changes UID (maybe the box gets rebuilt again) the job breaks.
> Update jenkins UID and bump verison to 2.0.0

- config.js
- package.json
- scripts/build-and-push-docker-image.sh
Currently we have hard coded URLs for some of our tests. We should handle this better but for the sake of brevity, this updates them to point at DOS3.
The version has a major and a minor bump on it because it looks like the major version was missed last time a breaking change was made (see changelog.)
> Update DOS2 urls for DOS3

- backstop_data/engine_scripts/casper/user.js
We don't want to give the impression that these credentials are actually for produciton users.
> Remove references to production users from envvars

- backstop_data/engine_scripts/casper/submitFormHelper.js
- config.js
In some pages (for instance `/suppliers/mailing-list`) the main form is the third child instead of the second.
This commit changes the selector so it gets the first child in a main tag, which should better exclude login/logout and feedback forms, which are outside this section.
This should fix the visual regression test bug discovered in https://trello.com/c/8HaNvlZ3/346-feedback-form-can-be-submitted-without-any-data, so this PR also restores the test that failed.
> Fix form selector

- config.js
* Adjust misMatchThreshold value down from 0.1 to 0
https://github.com/garris/BackstopJS#changing-test-sensitivity
https://trello.com/c/7nUNBc6c/766-visual-regression-not-regressing
> 766-visual-regression-not-regressing

- Dockerfile
- backstop_data/engine_scripts/casper/login.js
- backstop_data/engine_scripts/puppeteer/clearCookies.js
- backstop_data/engine_scripts/puppeteer/clickAndHoverHelper.js
- backstop_data/engine_scripts/puppeteer/login.js
- backstop_data/engine_scripts/puppeteer/onBefore.js
- backstop_data/engine_scripts/puppeteer/onReady.js
- backstop_data/engine_scripts/puppeteer/submitFormHelper.js
- backstop_data/engine_scripts/puppeteer/user.js
- config.js
- package-lock.json
- package.json
- scripts/build-and-push-docker-image.sh
Ticket: https://trello.com/c/JaWftHN8/492-upgrade-backstopjs-for-visual-regression-tests
This PR bumps our version of BackstopJS to the latest stable version. The biggest change is that it now uses Chrome and Puppeteer as the browser engine, rather than the (deprecated) PhantomJS engine. This meant I had to write some new engine scripts, but that shouldn't mean any loss in functionality.
This means that this PR will break *all* our visual regression tests; there are small changes in font rendering, form shadows etc. that make the images different. However, from local tests I haven't any seen any functional changes in how our pages appear.
The latest version of BackstopJS also comes with some cool Docker integration that should mean that we can get rid of our own Dockerfile; however, I'm …
> Upgrade backstopjs to v3.9.x

- backstop_data/engine_scripts/puppeteer/clickAndHoverHelper.js
- package-lock.json
- package.json
Our visual regression tests are occasionaly seeing differences because
the mouse happens to be hovering over a link and causing it to change
state; this PR should fix that by moving the mouse to the top-left
corner every time.
> Fix flakiness with hovering

- backstop_data/engine_scripts/puppeteer/login.js
Ticket: https://trello.com/c/hRR3O2AX/61-fix-visual-regression-scripts-to-work-with-buttons-from-digital-marketplace-frontend-toolkit-and-govuk-frontend
As part of migrating our frontends to use GOV.UK Design System components, we replaced the buttons in our user frontend (see alphagov/digitalmarketplace-user-frontend#167).
This also had the effect of breaking our visual regression tests, because our script to login to the frontend was looking for the old button class.
This PR changes the script to work with both old and new style buttons, so it should work against preview and staging.
> Fix login script

- config.js
We've had an issue where the styling on the error pages for some of apps has been altered as part of the frontend migration; we want to catch such issues in future, so this PR adds the 404 page for each app to the visual regression tests.
I can't off the top of my head think of any easy way to add the other error pages, but as the error page templates are all fairly similar this should catch most issues.
> Add error pages

- backstop_data/engine_scripts/puppeteer/user.js
- config.js
We want more confidence when making changes to the admin frontend such as https://github.com/alphagov/digitalmarketplace-admin-frontend/pull/591.
This PR adds more admin user roles to the visual regression tests, and more tests of the admin dashboard.
> Add more tests for admin dashboard with more user roles

- backstop_data/engine_scripts/puppeteer/clickAndHoverHelper.js
- config.js
We found an issue with the buyer create account error page (see alphagov/digitalmarketplace-briefs-frontend#249), so we're adding it to the visual regression tests.
We can do this because the engine scripts for BackstopJS now supports entering text into forms!
> Add a scenario for the buyer invalid domain error page

- config.js
We want to catch any visual regressions to our service/opportunity description pages. This commit adds an example of these pages to the visual regression suite.
The page was chosen at the beginning of the frontend migration mission based on being the most recently awarded opportunity; see https://trello.com/c/Cf71av8D/ for details.
> Add an example DOS opportunity

- config.js
Ticket: https://trello.com/c/xHWm8kLO/1412-visual-regression-test-flakiness
We've been having issues where our visual regression tests have been failing with images that are similar but have slightly different heights (mainly with mobile and tablet viewports).
This PR changes our configuration to allow images to have different dimensions. This should hopefully fix most if not all of the flakiness.
> Change mismatch test to allow images of different dimensions

- config.js
Set the live DOS framework as a variable and build URLs from the variable. This allows us to have different DOS frameworks live on each environment and keep the same tests.
These are all the VR tests which point to a DOS4 URL. There's one which looks at a DOS3 URL `"/admin/agreements/digital-outcomes-and-specialists-3?status=on-hold"`, but that's passing on Preview as is so I'll leave it alone
> Change tests on Preview to DOS5

- package-lock.json
- package.json
Reverts alphagov/digitalmarketplace-visual-regression#58
Not entirely sure why, but this seems to have broken things. After we merged this, the visual regression tests sometimes failed to load the fonts properly.
> Revert "Bump backstopjs from 5.0.6 to 5.1.0"

- package-lock.json
- package.json
Reverts alphagov/digitalmarketplace-visual-regression#62
We got a lot of weird visual changes, boxes overflowing, some pages being cropped[[1]], let's stick with the old working version.
[1]: https://ci.marketplace.team/job/visual-regression-preview/3225/Visual_Regression_Test_Report
> Revert "Bump backstopjs from 5.0.6 to 5.3.0"

- backstop_data/engine_scripts/puppeteer/onReady.js
- package-lock.json
- package.json
On `backstopjs` 5.1 and above we were seeing test failures with very minor rendering differences to the reference images, and also fonts not always loading.
We are not the only people seeing these problems - see [[1]] and [[2]]. In those issues, the author of `backstopjs` suggests that this is actually an issue with `puppeteer`, and another user suggests adding these lines to `onReady.js` to force the engine to wait for the fonts to load and ensure the window is always in the same place before taking a screenshot.
This _should_ fix the issues we've been having. I've tested it locally against my local version of the DMp and have been unable to see the same problems over several runs. I've also tried running the tests locally against preview which also seemed fine. The real test, however …
> Upgrade `backstopjs` to 5.3.2

- backstop_data/engine_scripts/puppeteer/onReady.js
- package-lock.json
- package.json
On backstopjs 5.1 and above we were seeing test failures with very minor rendering differences to the reference images, and also fonts not always loading.
We are not the only people seeing these problems - see [1] and [2]. In those issues, the author of backstopjs suggests that this is actually an issue with puppeteer, and another user suggests adding these lines to onReady.js to force the engine to wait for the fonts to load and ensure the window is always in the same place before taking a screenshot.
We already merged this in #68, however reverted it in #69 because we thought it hadn't fixed the problems. I opened a new PR rather than reverting the revert so out Git history is a bit more sensible.
Some more research showed that the CSS problems with text overflow on mobile are actually …
> Bump backstopjs to 5.3.2

- config.js
- package-lock.json
- package.json
https://trello.com/c/Lj7EZIoV/2208-upgrade-backstop-in-digitalmarketplace-visual-regression
We've had great trouble with the newer versions of Backstop (https://github.com/alphagov/digitalmarketplace-visual-regression/pull/72): after upgrading, we see a lot of flakiness due to fonts not rendering.
From my testing, it seems as if the flakiness disappears when I limit BackStopJS to capturing only one thing at a time. This seems to fix the issue without a major impact on run time. Let's see what impact this has when run on Jenkins.
I don't know what the underlying problem is - it could be a local problem, or a problem with the Digital Marketplace itself. I've hit a brick wall - I don't know enough about how this all works to be able to diagnose the problem in a reasonable amount of time. So …
> Upgrade to BackstopJS 5.3.5

- config.js
https://trello.com/c/Lj7EZIoV/2208-upgrade-backstop-in-digitalmarketplace-visual-regression
We need to limit the number of tests that can run in parallel. Something (I don't know what?) messes up font loading otherwise. The problem is that the tests are nearly twice as slow with no parallelism as they were with the default (10). This will waste our time during deploys.
See whether we can get the best of both worlds by allowing a small amount of parallelism. Locally, this seems stable to me, so I want to see how it performs on Jenkins. This is probably near the limit, though - I started to get errors at 4.
> Allow two tests to run in parallel

- config.js
I have removed/fixed some tests that were not working due to g-cloud-12 not being live anymore.
I've also updated Ruby to the latest version
> Remove tests that cannot be run now g-cloud-12 is expired

- .github/dependabot.yml
Reverts Crown-Commercial-Service/digitalmarketplace-visual-regression#95
I now realise that this is not necessary
> Revert "Add dependabot check for GitHub Actions"
